### ISSUE TITLE
[BUG] Rolling Saving Throws

### ISSUE THREAD

**Issue by Sphinx2k** [MangoFVTT/fvtt-ready-set-roll-5e#208]
I can't roll saving throws any more when the module is active. This is the error i get.
Foundry V10 291
Dnd5e 2.2.1
Ready Set Roll 1.5.1
Libwrapper 1.12.12.1

Tested it with a new game instance with only RSR + libwrapper as only active modules.

```
commons.js:2158 Uncaught (in promise) TypeError: undefined. key.split is not a function or its return value is not iterable
[Detected 1 package: ready-set-roll-5e]
    at Object.getProperty (commons.js:2158:24)
    at Localization.localize (foundry.js:6824:27)
    at CoreUtility.localize (core.js:28:26)
    at RollUtility.rollAbilitySave (roll.js:176:38)
    at Actor5e._actorRollAbilitySave (patching.js:96:40)
getProperty	@	commons.js:2158
localize	@	foundry.js:6824
localize	@	core.js:28
rollAbilitySave	@	roll.js:176
_actorRollAbilitySave	@	patching.js:96
Promise.then (async)		
🎁call_wrapper	@	libWrapper-wrapper.js:626
🎁CONFIG.Actor.documentClass.prototype.rollAbilitySave#0	@	libWrapper-wrapper.js:189
callback	@	actor.mjs:1202
submit	@	foundry.js:56403
_onClickButton	@	foundry.js:56332
dispatch	@	jquery.min.js:2
y.handle	@	jquery.min.js:2
```

**Comment by liquidsn8ke** [comment]
I get the same error on abilitie checks and saving throws
