### ISSUE TITLE
[BUG] Cannot use an item in dnd5e v2.4.0

### ISSUE THREAD

**Issue by kaelad02** [MangoFVTT/fvtt-ready-set-roll-5e#263]
**Description**
I had heard on Discord that there were issues with RSR after the dnd5e v2.4.0 update but I hadn't seen an issue on GitHub yet. I figured I'd test on a fresh world and file a bug in case you weren't aware yet. I imported one of the starter heroes the system comes with and tried to use a weapon and it results in an error.

```
Uncaught (in promise) TypeError: Cannot set property hasResource of #<Item5e> which has only a getter
    at ItemUtility.ensurePropertiesOnItem (item.js:197:30)
    at ItemUtility.refreshFlagsOnItem (item.js:303:21)
    at ItemUtility.ensureFlagsOnitem (item.js:236:14)
    at ItemUtility.getRollConfigFromItem (item.js:127:21)
    at RollUtility.rollItemWrapper (roll.js:104:71)
    at _itemProcessWrapper (patching.js:186:30)
    at Item5e._itemUse (patching.js:145:18)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁CONFIG.Item.documentClass.prototype.use#0 (libWrapper-wrapper.js:189:20)
    at ActorSheet5eCharacter._onItemUse (base-sheet.mjs:1136:17)
    at HTMLDivElement.<anonymous> (base-sheet.mjs:679:62)
    at HTMLDivElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```

From what I could tell, using weapons and features resulted in this error. When I cast spells, they worked fine.

**Steps to Reproduce**
1. Import Akra, the starter hero the system includes
2. Open the sheet and click on the Morningstar weapon
3. Nothing seems to happen, no chat message is generated or rolls made
4. See error in the console

**Versions**
 - Module: 2.1.3
 - dnd5e: 2.4.0
 - Foundry: 11.313

**Other Modules**
N/A, no other modules were enabled

**Comment by kaelad02** [comment]
I did a bit more testing and saw the same error occur when leveling up a PC. Level 2 on this PC added items for Channel Divinity which is what seemed to trigger the error. The first few lines in the stack trace are the same, but in case it helps, here's the full thing:

```
Ready Set Roll | Refreshing rsr5e item flags.
Foundry VTT | Error thrown in hooked function '' for hook 'createItem'
TypeError: Error thrown in hooked function '' for hook 'createItem'. Cannot set property hasResource of #<Item5e> which has only a getter
    at ItemUtility.ensurePropertiesOnItem (item.js:197:30)
    at ItemUtility.refreshFlagsOnItem (item.js:303:21)
    at ItemUtility.ensureFlagsOnitem (item.js:236:14)
    at Object.fn (hooks.js:110:25)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ClientDatabaseBackend.callback (foundry.js:13545:13)
    at foundry.js:13517:43
    at Array.map (<anonymous>)
    at #handleCreateDocuments (foundry.js:13517:33)
    at async Item5e.createDocuments (commons.js:7953:23)
    at async Promise.all (index 1)
    at async AdvancementManager._complete (advancement-manager.mjs:679:5)
```

**Comment by n-depinto** [comment]
I can also confirm this behavior after updating to D&D5E 2.4.0.

Versions

- Module: 2.1.3
- dnd5e: 2.4.0
- Foundry: 11.315

**Comment by Fatalmac77** [comment]
I have the same problem. I restored the 2.3.1 version of DnD and everything works fine.

**Comment by CarlNelson** [comment]
Same here. Restored back to 2.3.1 for now.

**Comment by MangoFVTT** [comment]
Issue has been resolved and will be in next release.
