### ISSUE TITLE
[BUG] dnd5e System 3.0.1 prevents rolls

### ISSUE THREAD

**Issue by ohmusama** [MangoFVTT/fvtt-ready-set-roll-5e#308]
**Description**
Rolls fail with exception from the dnd5e system.

at-message.mjs:235 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'formula')
[Detected 1 package: system:dnd5e]
    at ChatMessage5e._enrichRollTooltip (chat-message.mjs:235:54)
    at chat-message.mjs:219:51
    at NodeList.forEach (<anonymous>)
    at ChatMessage5e._enrichChatCard (chat-message.mjs:218:46)
    at ChatMessage5e.getHTML (chat-message.mjs:58:10)
    at async ChatLog.postOne (foundry.js:85744:18)

**Steps to Reproduce**
1. Roll any action on an actor
2. See error in console

**Versions**
 - Ready Set Roll: [2.1.7]
 - libwrapper: [1.12.13.0]
 - dnd5e: [3.0.1]
 - Foundry: [11.315]

**Other Modules**
None

**Comment by MangoFVTT** [comment]
DnD 5e 3.0.0+ is not yet supported, progress on the update is being tracked in #305. Closing this ticket as a duplicate
