### ISSUE TITLE
[BUG] [V12] Roll evaluate (async false) has been removed

### ISSUE THREAD

**Issue by strongpauly** [MangoFVTT/fvtt-ready-set-roll-5e#432]
**Description**
In Foundry version 12 they have removed the `async` option from the `evaluate` method on a roll which causes this module to throw errors.

**Steps to Reproduce**
In v12, roll any ability with this module enabled.
```
Error: The async option for Roll#evaluate has been removed. Use Roll#evaluateSync for synchronous roll evaluation.
    at Object.logCompatibilityWarning (foundry-esm.js:4576:19)
    at Roll.evaluate (foundry-esm.js:60514:23)
    at RollUtility.ensureMultiRoll (roll.js:98:123)
    at _enforceDualRolls (chat.js:211:50)
    at ChatUtility.processChatMessage (chat.js:54:19)
    at Object.fn (hooks.js:137:25)
    at #call (foundry.js:608:20)
    at Hooks.callAll (foundry.js:565:17)
    at ChatMessage5e.getHTML (chat-message.mjs:83:11)
    at async ChatLog.postOne (foundry.js:88879:18)
```

```
core.js:74 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at core.js:74:35
    at Array.forEach (<anonymous>)
    at CoreUtility.tryRollDice3D (core.js:73:9)
    at RollUtility.ensureMultiRoll (roll.js:100:31)
    at _enforceDualRolls (chat.js:211:50)
    at ChatUtility.processChatMessage (chat.js:54:19)
    at Object.fn (hooks.js:137:25)
    at #call (foundry.js:608:20)
    at Hooks.callAll (foundry.js:565:17)
    at ChatMessage5e.getHTML (chat-message.mjs:83:11)
    at async ChatLog.postOne (foundry.js:88879:18)
```

**Versions**
 - Module: [3.0.14]
 - dnd5e: [3.1.2]
 - Foundry: [12.322]

**Comment by strongpauly** [comment]
Any update on this?  This is the last module preventing me from upgrading to v12.

**Comment by MangoFVTT** [comment]
@strongpauly Working on updates to v12 now. Apologies for the delay, it was unavoidable due to other life commitments that take priority over this module.

**Comment by strongpauly** [comment]
Don't worry.  Thanks for the update!

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release.
