### ISSUE TITLE
[BUG]Can't installed

### ISSUE THREAD

**Issue by myblackpool** [MangoFVTT/fvtt-ready-set-roll-5e#546]
**Description**
<img width="1920" alt="3232" src="https://github.com/user-attachments/assets/a451daf2-20b4-4346-a796-716f3aaa5e1d">

I can't install in FVTT get error
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
    at checkPackage (file:///I:/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1179)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.installPackage (file:///I:/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:2011)
    at async SetupView.handlePost (file:///I:/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:2113)
    
    and i can't install it from FVTT modules file
**Versions**
 - Module: [3.4.2]
 - dnd5e: [4.4.1]
 - Foundry: [12.331]

**Other Modules**
A list of any other installed modules that might be related to the issue.

**Comment by MangoFVTT** [comment]
@myblackpool This is likely an error with corrupted download data from your end. Try completely deleting the ready-set-roll folder from your userdata, then reinstalling from scratch
