### ISSUE TITLE
[BUG] Bastions breaking with RSR enabled.

### ISSUE THREAD

**Issue by Ravaner1337** [MangoFVTT/fvtt-ready-set-roll-5e#548]
**Description**
**Steps to Reproduce**
1. Go to the bastion tab in the DND 5E System.
2. Click on Bastions and issue any order such as Craft,Trade,Recruit.
3. Expected Result : A window should pop up about your order and allowing you to confirm.
5. No window pops up and no bastion order is issued. This is fixed when disabling Ready Set Roll.

**Versions**
 - Module: Ready Set Roll Version 3.4.2
 - dnd5e: Version 4.1.1
 - Foundry: Version 12 build 331.

**Other Modules**
Seems to be only affected by roll modules such as RSR.

**Comment by MangoFVTT** [comment]
@Ravaner1337 I do not have any access to the DMG module yet and as such no easy way to test Bastion orders. If you can export one of the facility items that is breaking for you so I can import it accordingly, that would make it possible for me to fix this ticket

**Comment by Ravaner1337** [comment]
Here is an atttempt of remaking the greenhouse from 5E, it's suppose to grant you a health potion once the turn ends but does nothing. 
[fvtt-Item-greenhouse-VSGU3zuW46LUrnK0.json](https://github.com/user-attachments/files/18050694/fvtt-Item-greenhouse-VSGU3zuW46LUrnK0.json)

**Comment by MangoFVTT** [comment]
@Ravaner1337 No examples need that should be sufficient 👍  I'm currently abroad until early January over the Christmas holidays, so I don't have access to my dev environment (hence the delay). I'll look into the fix for this once I return

**Comment by xthesaintx** [comment]
Console error when using Bastions Harvest / Issue order

**With no modules activated**
[ActivityChoiceDialog, div#app-5.application.dnd5e2.activity-choice]
0 : ActivityChoiceDialog {#events: {…}, #id: 'app-5', #renderable: true, #element: div#app-5.application.dnd5e2.activity-choice, #content: section.window-content, …}
1 : div#app-5.application.dnd5e2.activity-choice

**With RSR Activated**
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'days')
    at OrderActivity._usageChatContext (order.mjs:240:16)
    at OrderActivity._createUsageMessage (mixin.mjs:931:32)
    at OrderActivity.use (mixin.mjs:291:38)

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release
